from local_agent import LLMAgent
from typing import Final


agent = LLMAgent("tiiuae/Falcon3-10B-Instruct")

promptTemplate: Final= """
You will be given the text of a scientific paper and a claim which was generated based on the content of the paper. 
You can assume that all information in the paper is factually correct. Your job is, that for the given claim you should extract the section of the paper which provides the 
best factual basis for justifying the statement. For that you should at least extract one sentence and up to 5 sentences which must be consecutively present in the paper. 
The extraction can only contain sentences that are directly quoted as they are written in the document. You are not allowed to make any adjustments whatsoever to them.
Here is a list of criteria that defines what a good
extraction looks like:

-The claim is the logical consequence of the facts in the context

-The claim and the context cover the same topic
-each topic that is present in the claim is also covered in the context

-the context does not contradict the claim
-the claim includes only information provided in the context or correct generalizations or interpretations of that information

-the context includes every piece of information needed to justify each individual piece of the claim

-the context and the claim convey the same meaning, even though the claim might be worded differently
-the context includes every semantic entity that is present in the claim

-the information in the context is unambiguous and its interpretation can only lead to the logical conclusions that are drawn in the claim

Search for the context, that fullfills all those criteria the best.

Input: 
-text of a scientific paper
-claim generated by an LLM on the basis of this paper

Output:
-The extracted context

Answer with only the extracted sentences, exactly as they are consecutively! written in the document
You are not allowed to hallucinate or make any adjustments to the sentences. You are also now allowed to add additional comments or headllines.
Strictly reply with only those sentences. 
Try to select as few sentences as possible. The response must include every information needed to fullfill the criteria, but should not contain any unnecessary information,
that is not needed to justify the claim.


Scientific Paper Text : "{paperText}"
Claim: "{claim}"

"""



